# shellcheck disable=SC2148
FROM opensuse/tumbleweed@sha256:a5ea0e92013001b7e0e0084e36619b28c39b46bfbf3dac6908a3174d85870f52

RUN zypper refresh && \
    zypper addrepo https://download.opensuse.org/repositories/openSUSE:Tools/openSUSE_Tumbleweed/openSUSE:Tools.repo && \
    zypper --gpg-auto-import-keys refresh && \
    zypper install -y osc build git curl wget && \
    zypper clean -a

WORKDIR /workspace

CMD ["/bin/bash"]