# shellcheck disable=SC2148
FROM opensuse/tumbleweed@sha256:6eefec6111343490a015cfc67a3a2578bb9f45c28296f88aa9f30e64ef35fbf3

RUN zypper refresh && \
    zypper addrepo https://download.opensuse.org/repositories/openSUSE:Tools/openSUSE_Tumbleweed/openSUSE:Tools.repo && \
    zypper --gpg-auto-import-keys refresh && \
    zypper install -y osc build git curl wget && \
    zypper clean -a

WORKDIR /workspace

CMD ["/bin/bash"]