packages:
  - frontend

allowBuilds:
  oxc-resolver: true

overrides:
  '@codecov/vite-plugin>vite': ^8.0.3
  undici: ^8.11.2

peerDependencyRules:
  allowedVersions:
    '@codecov/vite-plugin>vite': '8'
