[target.x86_64-unknown-linux-gnu]
linker = "wrapper/zig-cc"
rustflags = [
  "-Clink-arg=-target x86_64-linux-gnu.2.36",
]

[target.aarch64-unknown-linux-gnu]
linker = "wrapper/zig-cc"
rustflags = [
  "-Clink-arg=-target aarch64-linux-gnu.2.36",
]