pub(crate) mod port_forward;

pub(crate) mod built_info {
    // Generated by the `built` crate. Items inside are declared `pub` by the
    // crate's macro, so silence the visibility nag without touching upstream.
    #![allow(unreachable_pub)]
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}
