[package]
name = "kftray-network-monitor"
version = "0.20.4"
authors = ["Henrique Cavarsan <hencavarsan@gmail.com>"]
edition = "2021"
description = "Network monitoring and management for KFtray"
homepage = "https://kftray.app"
repository = "https://github.com/hcavarsan/kftray"
license = "MIT"

[dependencies]
kftray-commons = { path = "../kftray-commons" }
kftray-http-logs = { path = "../kftray-http-logs" }
kftray-portforward = { path = "../kftray-portforward" }
log = { workspace = true }
tokio = { workspace = true }