[package]
name = "kftray-http-logs"
version = "0.15.8"
description = "HTTP logging library for KFtray"
authors = [
    "Henrique Cavarsan <hencavarsan@gmail.com>",
]
license = "MIT"
homepage = "https://kftray.app"
repository = "https://github.com/hcavarsan/kftray"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytes = "1.9.0"
chrono = "0.4.39"
dashmap = "6.1.0"
dirs = "6.0.0"
flate2 = "1.0"
httparse = "1.9.5"
lazy_static = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros", "full"] }
tracing = "0.1.41"
uuid = { version = "1.11.1", features = ["v4"] }
brotli = "8.0.1"
kftray-commons = { path = "../kftray-commons" }

[dev-dependencies]
tempfile = "3.15.0"
mockall = "0.13.1"

[lib]
name = "kftray_http_logs"
path = "src/lib.rs"
