[package]
name = "kftray-commons"
version = "0.12.2"
description = "KFtray commons"
authors = [
    "Henrique Cavarsan <hencavarsan@gmail.com>",
]
license = "MIT"
homepage = "https://kftray.app"
repository = "https://github.com/hcavarsan/kftray"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bytes = "1.7.2"
dashmap = "6.1.0"
flate2 = "1.0"
httparse = "1.9.4"
k8s-openapi = { version = "0.23.0", default-features = false, features = ["latest"] }
lazy_static = "1.5.0"
log = "0.4"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros", "full"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4"] }
dirs = "5.0.1"
tauri = { version = "2.0", default-features = false, features = [
	"updater",
	"api-all",
	"macos-private-api",
	"system-tray",
	"icon-png",
	"devtools",
] }
sqlx = { version = "0.8.2", default-features = false, features = ["sqlite", "runtime-tokio-native-tls"] }
hostsfile = { git = "https://github.com/tonarino/innernet", branch = "main" }
tempfile = "3.13.0"
portpicker = "0.1.1"

[lib]
name = "kftray_commons"
path = "src/lib.rs"
