name: PR

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 0
  RUST_BACKTRACE: 1

jobs:
  eslint-format:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 10
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Cache pnpm modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.pnpm-store
            node_modules
            frontend/node_modules
          key: pnpm-eslint-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-eslint-${{ runner.os }}-
            pnpm-${{ runner.os }}-

      - name: Perform linting
        run: pnpm lint:front

  rust-format:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331
        with:
          toolchain: nightly

      - name: Install Rust nightly
        run: rustup toolchain install nightly

      - name: Install rustfmt for nightly
        run: rustup component add --toolchain nightly rustfmt

      - name: Cache Rust
        uses: swatinem/rust-cache@972b315a8225e8594dddc2b92e6333d1d1d3059c
        with:
          key: rust-format-${{ runner.os }}
          shared-key: deps-format
          cache-on-failure: false

      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check

  rust-lint:
    name: Clippy
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            os_name: linux
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            os_name: macos
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            os_name: windows
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e

      - name: Install dependencies
        if: matrix.os_name == 'linux'
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331
        with:
          toolchain: nightly

      - name: Install OpenSSL on Windows
        if: matrix.os == 'windows-latest'
        run: choco install openssl

      - name: Set up Perl on Windows
        if: matrix.os == 'windows-latest'
        uses: shogo82148/actions-setup-perl@2c11cccccad676d30c3ea336055b243606aeca43
        with:
          perl-version: "5.32"
          distribution: "strawberry"

      - name: Set Perl environment variables
        if: matrix.os == 'windows-latest'
        run: |
          echo "PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "OPENSSL_SRC_PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Configure Rust targets
        run: rustup target add ${{ matrix.rust_target }}
        shell: bash

      - name: Cache Rust
        uses: swatinem/rust-cache@972b315a8225e8594dddc2b92e6333d1d1d3059c
        with:
          key: rust-lint-${{ matrix.os }}-${{ matrix.rust_target }}
          shared-key: deps-lint-${{ matrix.rust_target }}
          workspaces: |
            .
            crates/kftray-helper
          cache-on-failure: false

      - name: build kftray-helper
        run: cargo build --bin kftray-helper --release

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --allow-dirty --allow-staged --all-features --fix -- -D warnings

  rust-coverage:
    name: Code Coverage
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331
        with:
          toolchain: nightly

      - name: Install llvm-tools
        run: rustup component add llvm-tools

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@4b1e2228abe7b502befd5d976a44d7eea4ddc8e1
        with:
          tool: cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@4b1e2228abe7b502befd5d976a44d7eea4ddc8e1
        with:
          tool: cargo-nextest

      - name: Cache Rust
        uses: swatinem/rust-cache@972b315a8225e8594dddc2b92e6333d1d1d3059c
        with:
          key: rust-coverage-ci-${{ runner.os }}
          shared-key: deps-coverage-ci
          cache-directories: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          cache-on-failure: false

      - name: Install cargo-insta
        run: cargo install cargo-insta

      - name: Run tests
        run: cargo build --bin kftray-helper --release && INSTA_UPDATE=1 cargo llvm-cov nextest --profile ci --config-file .cargo/nextest.toml --locked --workspace --all-features --lib --bins --examples --tests --lcov --output-path lcov.info

      - name: Upload coverage
        uses: codecov/codecov-action@9b6d1f84bde660b0f784003009b1f0aa4663cdeb
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          slug: hcavarsan/kftray

      - name: Upload test results
        uses: codecov/test-results-action@3fef12b33cff40c3ba4a721741678dd3abebcd67
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          slug: hcavarsan/kftray

  frontend-bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: 10
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Cache pnpm modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.pnpm-store
            node_modules
            frontend/node_modules
          key: pnpm-bundle-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-bundle-${{ runner.os }}-
            pnpm-${{ runner.os }}-

      - name: Build frontend with bundle analysis
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: cd frontend && pnpm build

  build-and-push-docker:
    if: ${{ contains(github.event.pull_request.title, '[docker]') }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a

      - name: Login to GitHub Container Registry
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./crates/kftray-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kftray-server:${{ github.sha }}

