name: PR

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 0
  RUST_BACKTRACE: 1

jobs:
  eslint-format:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install pnpm
        uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0
        with:
          version: 10
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Perform linting
        run: pnpm lint:front

  rust-format:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
        with:
          toolchain: nightly

      - name: Install Rust nightly
        run: rustup toolchain install nightly

      - name: Install rustfmt for nightly
        run: rustup component add --toolchain nightly rustfmt

      - name: Run rustfmt
        run: cargo +nightly fmt --all -- --check

  rust-lint:
    name: Clippy
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            os_name: linux
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            os_name: macos
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            os_name: windows
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install dependencies
        if: matrix.os_name == 'linux'
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
        with:
          toolchain: nightly

      - name: Install OpenSSL on Windows
        if: matrix.os == 'windows-latest'
        run: choco install openssl

      - name: Set up Perl on Windows
        if: matrix.os == 'windows-latest'
        uses: shogo82148/actions-setup-perl@675da8e534b774539eeb9abb92db0aec8c727183
        with:
          perl-version: "5.32"
          distribution: "strawberry"

      - name: Set Perl environment variables
        if: matrix.os == 'windows-latest'
        run: |
          echo "PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "OPENSSL_SRC_PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Configure Rust targets
        run: rustup target add ${{ matrix.rust_target }}
        shell: bash

      - name: build kftray-helper
        run: cargo build --bin kftray-helper --release

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --allow-dirty --allow-staged --all-features --fix -- -D warnings

  rust-coverage:
    name: Code Coverage
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
        with:
          toolchain: nightly

      - name: Install llvm-tools
        run: rustup component add llvm-tools

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@e825cea3ae7859bea8ac6c1c1ecde4d7699f05b6
        with:
          tool: cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@e825cea3ae7859bea8ac6c1c1ecde4d7699f05b6
        with:
          tool: cargo-nextest

      - name: Install rust-cache
        uses: swatinem/rust-cache@a1f94902a6a14bb816df36cf064a35883424b553

      - name: Install cargo-insta
        run: cargo install cargo-insta

      - name: Run tests
        run: cargo build --bin kftray-helper --release && INSTA_UPDATE=1 cargo llvm-cov nextest --profile ci --config-file .cargo/nextest.toml --locked --workspace --all-features --lib --bins --examples --tests --lcov --output-path lcov.info

      - name: Upload coverage
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          slug: hcavarsan/kftray

      - name: Upload test results
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          slug: hcavarsan/kftray

  frontend-bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Install pnpm
        uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0
        with:
          version: 10
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Build frontend with bundle analysis
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: cd frontend && pnpm build

  build-and-push-docker:
    needs:
      [
        eslint-format,
        rust-format,
        rust-lint,
        rust-coverage,
        frontend-bundle-analysis,
      ]
    if: ${{ contains(github.event.pull_request.title, '[docker]') }}
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e77e8065d9f7ec6abdd9838668cd7b43924dd64d

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@1583c0f09d26c58c59d25b0eef29792b7ce99d9a

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          platforms: linux/amd64,linux/arm64
          context: ./crates/kftray-server
          file: ./crates/kftray-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kftray-server:${{ github.sha }}
