name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest-x64, windows-latest-arm]
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin --verbose --bundles dmg,updater'
          - platform: 'ubuntu-20.04'
            args: --verbose --bundles appimage,updater'
          - platform: 'windows-latest-x64'
            args: '--target x86_64-pc-windows-msvc --verbose --bundles nsis,updater'
          - platform: 'windows-latest-arm'
            args: '--target aarch64-pc-windows-msvc --verbose --bundles nsis,updater'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Rust target (macOS)
        if: matrix.platform == 'macos-latest'
        run: rustup target add x86_64-apple-darwin

      - name: Add Rust target (Windows AMD64)
        if: matrix.platform == 'windows-latest-x64'
        run: rustup target add x86_64-pc-windows-msvc

      - name: Add Rust target (Windows ARM)
        if: matrix.platform == 'windows-latest-arm'
        run: rustup target add aarch64-pc-windows-msvc

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libssl-dev

      - name: Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.1'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.6

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: |
            $(pnpm store path --silent)
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Rust target (Windows ARM)
        if: matrix.platform == 'windows-arm'
        run: rustup target add aarch64-pc-windows-msvc

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'KFtray - ${{ github.ref_name }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          updaterJsonKeepUniversal: true
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=6000

  build-and-push-docker:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./crates/kftray-server
          file: ./crates/kftray-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kftray-server:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/kftray-server:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/kftray-server:latest
