name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
  VITE_ENV: "production"
  TAURI_DEBUG: "false"

jobs:
  create-release-draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create release draft
        run: |
          echo "Creating release draft for tag: ${{ github.ref_name }}"
          gh release create ${{ github.ref_name }} --draft --title "KFtray - ${{ github.ref_name }}" --notes "See the assets to download this version and install."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  kftray-tauri:
    needs: create-release-draft
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: arm64
            runner: ubicloud-standard-4-arm
            rust_target: aarch64-unknown-linux-gnu
            tauri_args: "--target aarch64-unknown-linux-gnu --bundles appimage,updater --verbose"
          - os: ubuntu-latest
            arch: amd64
            rust_target: x86_64-unknown-linux-gnu
            tauri_args: "--target x86_64-unknown-linux-gnu --bundles appimage,updater --verbose"
          - os: macos-latest
            arch: universal
            rust_target: universal-apple-darwin
            tauri_args: "--target universal-apple-darwin --bundles dmg,updater --verbose"
          - os: windows-latest
            arch: x86
            rust_target: i686-pc-windows-msvc
            tauri_args: "--target i686-pc-windows-msvc --bundles nsis,updater --verbose"
            msvc_arch: x86
          - os: windows-latest
            arch: x86_64
            rust_target: x86_64-pc-windows-msvc
            tauri_args: "--target x86_64-pc-windows-msvc --bundles nsis,updater --verbose"
            msvc_arch: x64
          - os: windows-latest
            arch: arm64
            rust_target: aarch64-pc-windows-msvc
            tauri_args: "--target aarch64-pc-windows-msvc --bundles nsis,updater --verbose"

    runs-on: ${{ matrix.runner || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: swatinem/rust-cache@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.2

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: |
            $(pnpm store path --silent)
            **/node_modules
          key: ${{ runner.OS }}-pnpm-${{ runner.ARCH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-${{ runner.ARCH }}-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Set up Visual Studio shell
        if: matrix.os == 'windows-latest' && matrix.arch == 'arm64'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: amd64_arm64

      - name: Setup platform-specific dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libssl-dev

      - name: Reconfigure Rust targets
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            rustup target add aarch64-apple-darwin x86_64-apple-darwin
          else
            rustup target add ${{ matrix.rust_target }}
          fi
        shell: bash
      - name: Build kftray-tauri Desktop App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=6000
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "KFtray - ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          updaterJsonKeepUniversal: true
          args: ${{ matrix.tauri_args }}

  kftui:
    needs: create-release-draft
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: arm64
            runner: ubicloud-standard-4-arm
            rust_target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: amd64
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            arch: universal
            rust_target: universal-apple-darwin
          - os: windows-latest
            arch: x86
            rust_target: i686-pc-windows-msvc
            msvc_arch: x86
          - os: windows-latest
            arch: x86_64
            rust_target: x86_64-pc-windows-msvc
            msvc_arch: x64

    runs-on: ${{ matrix.runner || matrix.os }}

    outputs:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: swatinem/rust-cache@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.1.2

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: |
            $(pnpm store path --silent)
            **/node_modules
          key: ${{ runner.OS }}-pnpm-${{ runner.ARCH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-${{ runner.ARCH }}-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Setup platform-specific dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libssl-dev

      - name: Reconfigure Rust targets
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            rustup target add aarch64-apple-darwin x86_64-apple-darwin
          else
            rustup target add ${{ matrix.rust_target }}
          fi
        shell: bash

      - name: Build kftui
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            cargo build --release --bin kftui --target aarch64-apple-darwin
            cargo build --release --bin kftui --target x86_64-apple-darwin
            lipo -create -output ./target/release/kftui ./target/x86_64-apple-darwin/release/kftui ./target/aarch64-apple-darwin/release/kftui
          else
            cargo build --release --bin kftui --target ${{ matrix.rust_target }}
          fi
        shell: bash

      - name: Sign and notarize the release build
        if: matrix.os == 'macos-latest'
        uses: toitlang/action-macos-sign-notarize@v1.2.0
        with:
          certificate: ${{ secrets.APPLE_CERTIFICATE }}
          certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          username: ${{ secrets.APPLE_ID }}
          password: ${{ secrets.APPLE_PASSWORD }}
          apple-team-id: 6M376JWU73
          app-path: target/release/kftui
          entitlements-path: crates/kftui/entitlements.plist

      - name: Staple the notarization ticket
        if: matrix.os == 'macos-latest'
        run: |
          xcrun stapler staple target/release/kftui
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: 6M376JWU73

      - name: Verify the stapling
        if: matrix.os == 'macos-latest'
        run: |
          spctl -a -v target/release/kftui


      - name: Extract TUI version
        if: matrix.os != 'windows-latest'
        id: extract_version
        run: |
          TUI_VERSION=$(cargo metadata --format-version=1 | jq -r '.packages[] | select(.name == "kftui") | .version')
          echo "TUI_VERSION=$TUI_VERSION" >> $GITHUB_ENV
          echo "Extracted TUI_VERSION: $TUI_VERSION"

      - name: Extract TUI version
        if: matrix.os == 'windows-latest'
        id: extract_version_windows
        run: |
          $TUI_VERSION = Invoke-Expression "cargo metadata --format-version=1 | jq -r '.packages[] | select(.name == ""kftui"") | .version'"
          echo "TUI_VERSION=$TUI_VERSION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "Extracted TUI_VERSION: $TUI_VERSION"
        shell: pwsh

      - name: Rename and upload release asset
        run: |
          echo "Running TUI_VERSION=$TUI_VERSION"
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            mv ./target/release/kftui ./target/release/kftui_${TUI_VERSION}_macos-universal
            chmod +x ./target/release/kftui_${TUI_VERSION}_macos-universal
            gh release upload ${{ github.ref_name }} ./target/release/kftui_${TUI_VERSION}_macos-universal --clobber
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv ./target/${{ matrix.rust_target }}/release/kftui.exe ./target/release/kftui_${TUI_VERSION}_${{ matrix.os }}_${{ matrix.arch }}.exe
            chmod +x ./target/release/kftui_${TUI_VERSION}_${{ matrix.os }}_${{ matrix.arch }}.exe
            gh release upload ${{ github.ref_name }} ./target/release/kftui_${TUI_VERSION}_${{ matrix.os }}_${{ matrix.arch }}.exe --clobber
          else
            mv ./target/${{ matrix.rust_target }}/release/kftui ./target/release/kftui_${TUI_VERSION}_${{ matrix.os }}_${{ matrix.arch }}
            chmod +x ./target/release/kftui_${TUI_VERSION}_${{ matrix.os }}_${{ matrix.arch }}
            gh release upload ${{ github.ref_name }} ./target/release/kftui_${TUI_VERSION}_${{ matrix.os }}_${{ matrix.arch }} --clobber
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        shell: bash

  kftray-server:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./crates/kftray-server
          file: ./crates/kftray-server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kftray-server:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/kftray-server:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/kftray-server:latest
